export default {
  appLogo: require("../assets/images/appLogo.png"),
  spashSvg: require("../assets/svg/splash.svg"),
  spashImage: require("../assets/images/splash.png"),
  onBoardHeader: require("../assets/images/onBoardHeader.png"),
  mainHeader: require("../assets/images/mainHeader.png"),
  onBoardHeader: require("../assets/images/onBoardHeader.png"),
  arrowLeft: require("../assets/images/arrowLeft.png"),
  arrowLeftSvg: require("../assets/svg/arrowLeft.svg"),
  arrowRight: require("../assets/images/arrowRight.png"),
  arrowRightSvg: require("../assets/svg/arrowRight.svg"),
  dashboardFillSvg: require("../assets/svg/dashboardFill.svg"),
  dashboardFill: require("../assets/images/dashboardFill.png"),
  dashboardOutline: require("../assets/images/dashboardOutline.png"),
  logoutOutline: require("../assets/images/logoutOutline.png"),
  logoutFill: require("../assets/images/logoutFilled.png"),
  receiveFill: require("../assets/images/receiveFilled.png"),
  receiveOutline: require("../assets/images/receiveOutline.png"),
};
